In [ ]:
import pandas as pd

df_pm25 = pd.read_csv("/Users/cawenosu/Downloads/IS 477 Air quality dataset/dailyPM2.5_88101_2024.csv")

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,PM2.5 - Local Conditions,2024-01-02,Micrograms/cubic meter (LC),10,42.0,8.410000
1,Alabama,PM2.5 - Local Conditions,2024-01-03,Micrograms/cubic meter (LC),24,100.0,7.420833
2,Alabama,PM2.5 - Local Conditions,2024-01-04,Micrograms/cubic meter (LC),24,100.0,6.933333
3,Alabama,PM2.5 - Local Conditions,2024-01-05,Micrograms/cubic meter (LC),24,100.0,7.900000
4,Alabama,PM2.5 - Local Conditions,2024-01-06,Micrograms/cubic meter (LC),24,100.0,1.270833
...,...,...,...,...,...,...,...
738473,Country Of Mexico,PM2.5 - Local Conditions,2024-12-27,Micrograms/cubic meter (LC),1,100.0,18.200000
738474,Country Of Mexico,PM2.5 - Local Conditions,2024-12-28,Micrograms/cubic meter (LC),1,100.0,19.800000
738475,Country Of Mexico,PM2.5 - Local Conditions,2024-12-29,Micrograms/cubic meter (LC),1,100.0,26.000000
738476,Country Of Mexico,PM2.5 - Local Conditions,2024-12-30,Micrograms/cubic meter (LC),1,100.0,19.800000
738477,Country Of Mexico,PM2.5 - Local Conditions,2024-12-31,Micrograms/cubic meter (LC),1,100.0,29.500000

In [8]:
df_co = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/dailyCO_42101_2024.csv')
df_co

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Carbon monoxide,2024-01-01,Parts per million,24,100.0,0.170833
1,Alabama,Carbon monoxide,2024-01-02,Parts per million,24,100.0,0.287500
2,Alabama,Carbon monoxide,2024-01-03,Parts per million,24,100.0,0.504167
3,Alabama,Carbon monoxide,2024-01-04,Parts per million,24,100.0,0.287500
4,Alabama,Carbon monoxide,2024-01-05,Parts per million,24,100.0,0.216667
...,...,...,...,...,...,...,...
148817,Puerto Rico,Carbon monoxide,2024-12-27,Parts per million,24,100.0,0.266667
148818,Puerto Rico,Carbon monoxide,2024-12-28,Parts per million,24,100.0,0.266667
148819,Puerto Rico,Carbon monoxide,2024-12-29,Parts per million,24,100.0,0.254167
148820,Puerto Rico,Carbon monoxide,2024-12-30,Parts per million,24,100.0,0.283333
148821,Puerto Rico,Carbon monoxide,2024-12-31,Parts per million,7,29.0,0.300000

In [9]:
df_no2 = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/dailyNO2_42602_2024.csv')
df_no2

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Nitrogen dioxide (NO2),2024-01-01,Parts per billion,24,100.0,4.366667
1,Alabama,Nitrogen dioxide (NO2),2024-01-02,Parts per billion,24,100.0,14.983333
2,Alabama,Nitrogen dioxide (NO2),2024-01-03,Parts per billion,24,100.0,25.695833
3,Alabama,Nitrogen dioxide (NO2),2024-01-04,Parts per billion,24,100.0,11.766667
4,Alabama,Nitrogen dioxide (NO2),2024-01-05,Parts per billion,24,100.0,10.854167
...,...,...,...,...,...,...,...
154716,Wyoming,Nitrogen dioxide (NO2),2024-12-27,Parts per billion,22,92.0,0.872727
154717,Wyoming,Nitrogen dioxide (NO2),2024-12-28,Parts per billion,24,100.0,0.550000
154718,Wyoming,Nitrogen dioxide (NO2),2024-12-29,Parts per billion,24,100.0,0.762500
154719,Wyoming,Nitrogen dioxide (NO2),2024-12-30,Parts per billion,22,92.0,1.159091
154720,Wyoming,Nitrogen dioxide (NO2),2024-12-31,Parts per billion,24,100.0,1.079167

In [10]:
df_ozone = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/dailyOzone_44201_2024.csv')
df_ozone

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Ozone,2024-02-29,Parts per million,1,6.0,0.032000
1,Alabama,Ozone,2024-03-01,Parts per million,17,100.0,0.024706
2,Alabama,Ozone,2024-03-02,Parts per million,17,100.0,0.013118
3,Alabama,Ozone,2024-03-03,Parts per million,17,100.0,0.033941
4,Alabama,Ozone,2024-03-04,Parts per million,17,100.0,0.032471
...,...,...,...,...,...,...,...
387029,Country Of Mexico,Ozone,2024-12-27,Parts per million,17,100.0,0.015235
387030,Country Of Mexico,Ozone,2024-12-28,Parts per million,17,100.0,0.016353
387031,Country Of Mexico,Ozone,2024-12-29,Parts per million,17,100.0,0.019235
387032,Country Of Mexico,Ozone,2024-12-30,Parts per million,17,100.0,0.018706
387033,Country Of Mexico,Ozone,2024-12-31,Parts per million,12,71.0,0.027333

In [11]:
df_so2 = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/dailySO2_42401_2024.csv')
df_so2

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Sulfur dioxide,2024-01-01,Parts per billion,24,100.0,1.041667
1,Alabama,Sulfur dioxide,2024-01-02,Parts per billion,24,100.0,1.537500
2,Alabama,Sulfur dioxide,2024-01-03,Parts per billion,24,100.0,3.716667
3,Alabama,Sulfur dioxide,2024-01-04,Parts per billion,24,100.0,1.237500
4,Alabama,Sulfur dioxide,2024-01-05,Parts per billion,24,100.0,1.200000
...,...,...,...,...,...,...,...
268197,Puerto Rico,Sulfur dioxide,2024-10-25,Parts per billion,8,100.0,0.487500
268198,Puerto Rico,Sulfur dioxide,2024-10-26,Parts per billion,8,100.0,0.425000
268199,Puerto Rico,Sulfur dioxide,2024-10-27,Parts per billion,8,100.0,0.512500
268200,Puerto Rico,Sulfur dioxide,2024-10-28,Parts per billion,8,100.0,0.537500
268201,Puerto Rico,Sulfur dioxide,2024-10-29,Parts per billion,4,50.0,0.600000

In [12]:
df_all = pd.concat([df_pm25, df_co, df_no2,df_ozone,df_so2], ignore_index=True)

In [13]:
df_all

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,PM2.5 - Local Conditions,2024-01-02,Micrograms/cubic meter (LC),10,42.0,8.410000
1,Alabama,PM2.5 - Local Conditions,2024-01-03,Micrograms/cubic meter (LC),24,100.0,7.420833
2,Alabama,PM2.5 - Local Conditions,2024-01-04,Micrograms/cubic meter (LC),24,100.0,6.933333
3,Alabama,PM2.5 - Local Conditions,2024-01-05,Micrograms/cubic meter (LC),24,100.0,7.900000
4,Alabama,PM2.5 - Local Conditions,2024-01-06,Micrograms/cubic meter (LC),24,100.0,1.270833
...,...,...,...,...,...,...,...
1697252,Puerto Rico,Sulfur dioxide,2024-10-25,Parts per billion,8,100.0,0.487500
1697253,Puerto Rico,Sulfur dioxide,2024-10-26,Parts per billion,8,100.0,0.425000
1697254,Puerto Rico,Sulfur dioxide,2024-10-27,Parts per billion,8,100.0,0.512500
1697255,Puerto Rico,Sulfur dioxide,2024-10-28,Parts per billion,8,100.0,0.537500
1697256,Puerto Rico,Sulfur dioxide,2024-10-29,Parts per billion,4,50.0,0.600000