In [2]:
import pandas as pd

df_pm2524 = pd.read_csv("/Users/cawenosu/Downloads/IS 477 Air quality dataset/dailyPM2.5_88101_2024.csv")
df_pm2524

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,PM2.5 - Local Conditions,2024-01-02,Micrograms/cubic meter (LC),10,42.0,8.410000
1,Alabama,PM2.5 - Local Conditions,2024-01-03,Micrograms/cubic meter (LC),24,100.0,7.420833
2,Alabama,PM2.5 - Local Conditions,2024-01-04,Micrograms/cubic meter (LC),24,100.0,6.933333
3,Alabama,PM2.5 - Local Conditions,2024-01-05,Micrograms/cubic meter (LC),24,100.0,7.900000
4,Alabama,PM2.5 - Local Conditions,2024-01-06,Micrograms/cubic meter (LC),24,100.0,1.270833
...,...,...,...,...,...,...,...
738473,Country Of Mexico,PM2.5 - Local Conditions,2024-12-27,Micrograms/cubic meter (LC),1,100.0,18.200000
738474,Country Of Mexico,PM2.5 - Local Conditions,2024-12-28,Micrograms/cubic meter (LC),1,100.0,19.800000
738475,Country Of Mexico,PM2.5 - Local Conditions,2024-12-29,Micrograms/cubic meter (LC),1,100.0,26.000000
738476,Country Of Mexico,PM2.5 - Local Conditions,2024-12-30,Micrograms/cubic meter (LC),1,100.0,19.800000
738477,Country Of Mexico,PM2.5 - Local Conditions,2024-12-31,Micrograms/cubic meter (LC),1,100.0,29.500000

In [4]:
df_pm2525 = pd.read_csv("/Users/cawenosu/Downloads/IS 477 Air quality dataset/daily_PM2.5_88101_2025.csv")
df_pm2525

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,PM2.5 - Local Conditions,2025-01-01,Micrograms/cubic meter (LC),24,100.0,3.625000
1,Alabama,PM2.5 - Local Conditions,2025-01-01,Micrograms/cubic meter (LC),1,100.0,3.600000
2,Alabama,PM2.5 - Local Conditions,2025-01-01,Micrograms/cubic meter (LC),24,100.0,2.062500
3,Alabama,PM2.5 - Local Conditions,2025-01-01,Micrograms/cubic meter (LC),1,100.0,2.000000
4,Alabama,PM2.5 - Local Conditions,2025-01-01,Micrograms/cubic meter (LC),24,100.0,2.858333
...,...,...,...,...,...,...,...
241218,Wyoming,PM2.5 - Local Conditions,2025-04-30,Micrograms/cubic meter (LC),1,100.0,2.600000
241219,Wyoming,PM2.5 - Local Conditions,2025-04-30,Micrograms/cubic meter (LC),24,100.0,0.158333
241220,Wyoming,PM2.5 - Local Conditions,2025-04-30,Micrograms/cubic meter (LC),1,100.0,0.100000
241221,Country Of Mexico,PM2.5 - Local Conditions,2025-04-30,Micrograms/cubic meter (LC),24,100.0,10.995833
241222,Country Of Mexico,PM2.5 - Local Conditions,2025-04-30,Micrograms/cubic meter (LC),1,100.0,10.900000

In [5]:
df_co24 = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/dailyCO_42101_2024.csv')
df_co24

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Carbon monoxide,2024-01-01,Parts per million,24,100.0,0.170833
1,Alabama,Carbon monoxide,2024-01-02,Parts per million,24,100.0,0.287500
2,Alabama,Carbon monoxide,2024-01-03,Parts per million,24,100.0,0.504167
3,Alabama,Carbon monoxide,2024-01-04,Parts per million,24,100.0,0.287500
4,Alabama,Carbon monoxide,2024-01-05,Parts per million,24,100.0,0.216667
...,...,...,...,...,...,...,...
148817,Puerto Rico,Carbon monoxide,2024-12-27,Parts per million,24,100.0,0.266667
148818,Puerto Rico,Carbon monoxide,2024-12-28,Parts per million,24,100.0,0.266667
148819,Puerto Rico,Carbon monoxide,2024-12-29,Parts per million,24,100.0,0.254167
148820,Puerto Rico,Carbon monoxide,2024-12-30,Parts per million,24,100.0,0.283333
148821,Puerto Rico,Carbon monoxide,2024-12-31,Parts per million,7,29.0,0.300000

In [6]:
df_co25 = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/daily_CO_42101_2025.csv')
df_co25

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Carbon monoxide,2025-01-01,Parts per million,24,100.0,0.200000
1,Alabama,Carbon monoxide,2025-01-01,Parts per million,19,79.0,0.200000
2,Alabama,Carbon monoxide,2025-01-01,Parts per million,24,100.0,0.133333
3,Alabama,Carbon monoxide,2025-01-01,Parts per million,19,79.0,0.126316
4,Alabama,Carbon monoxide,2025-01-01,Parts per million,24,100.0,0.116667
...,...,...,...,...,...,...,...
47154,Wyoming,Carbon monoxide,2025-04-30,Parts per million,24,100.0,0.100000
47155,Puerto Rico,Carbon monoxide,2025-04-30,Parts per million,23,96.0,0.239130
47156,Puerto Rico,Carbon monoxide,2025-04-30,Parts per million,24,100.0,0.225000
47157,Puerto Rico,Carbon monoxide,2025-04-30,Parts per million,24,100.0,0.208333
47158,Puerto Rico,Carbon monoxide,2025-04-30,Parts per million,24,100.0,0.225000

In [7]:
df_no224 = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/dailyNO2_42602_2024.csv')
df_no224

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Nitrogen dioxide (NO2),2024-01-01,Parts per billion,24,100.0,4.366667
1,Alabama,Nitrogen dioxide (NO2),2024-01-02,Parts per billion,24,100.0,14.983333
2,Alabama,Nitrogen dioxide (NO2),2024-01-03,Parts per billion,24,100.0,25.695833
3,Alabama,Nitrogen dioxide (NO2),2024-01-04,Parts per billion,24,100.0,11.766667
4,Alabama,Nitrogen dioxide (NO2),2024-01-05,Parts per billion,24,100.0,10.854167
...,...,...,...,...,...,...,...
154716,Wyoming,Nitrogen dioxide (NO2),2024-12-27,Parts per billion,22,92.0,0.872727
154717,Wyoming,Nitrogen dioxide (NO2),2024-12-28,Parts per billion,24,100.0,0.550000
154718,Wyoming,Nitrogen dioxide (NO2),2024-12-29,Parts per billion,24,100.0,0.762500
154719,Wyoming,Nitrogen dioxide (NO2),2024-12-30,Parts per billion,22,92.0,1.159091
154720,Wyoming,Nitrogen dioxide (NO2),2024-12-31,Parts per billion,24,100.0,1.079167

In [8]:
df_no225 = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/daily_NO2_42602_2025.csv')
df_no225

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Nitrogen dioxide (NO2),2025-01-01,Parts per billion,24,100.0,4.566667
1,Arizona,Nitrogen dioxide (NO2),2025-01-01,Parts per billion,24,100.0,24.458333
2,Arizona,Nitrogen dioxide (NO2),2025-01-01,Parts per billion,24,100.0,26.791667
3,Arizona,Nitrogen dioxide (NO2),2025-01-01,Parts per billion,24,100.0,11.083333
4,Arizona,Nitrogen dioxide (NO2),2025-01-01,Parts per billion,24,100.0,34.083333
...,...,...,...,...,...,...,...
48184,Wyoming,Nitrogen dioxide (NO2),2025-04-30,Parts per billion,24,100.0,0.666667
48185,Wyoming,Nitrogen dioxide (NO2),2025-04-30,Parts per billion,19,79.0,3.215789
48186,Wyoming,Nitrogen dioxide (NO2),2025-04-30,Parts per billion,22,92.0,0.781818
48187,Wyoming,Nitrogen dioxide (NO2),2025-04-30,Parts per billion,19,79.0,0.831579
48188,Wyoming,Nitrogen dioxide (NO2),2025-04-30,Parts per billion,24,100.0,0.745833

In [9]:
df_ozone24 = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/dailyOzone_44201_2024.csv')
df_ozone24

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Ozone,2024-02-29,Parts per million,1,6.0,0.032000
1,Alabama,Ozone,2024-03-01,Parts per million,17,100.0,0.024706
2,Alabama,Ozone,2024-03-02,Parts per million,17,100.0,0.013118
3,Alabama,Ozone,2024-03-03,Parts per million,17,100.0,0.033941
4,Alabama,Ozone,2024-03-04,Parts per million,17,100.0,0.032471
...,...,...,...,...,...,...,...
387029,Country Of Mexico,Ozone,2024-12-27,Parts per million,17,100.0,0.015235
387030,Country Of Mexico,Ozone,2024-12-28,Parts per million,17,100.0,0.016353
387031,Country Of Mexico,Ozone,2024-12-29,Parts per million,17,100.0,0.019235
387032,Country Of Mexico,Ozone,2024-12-30,Parts per million,17,100.0,0.018706
387033,Country Of Mexico,Ozone,2024-12-31,Parts per million,12,71.0,0.027333

In [10]:
df_ozone25 = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/daily_Ozone_44201_2025.csv')
df_ozone25

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Ozone,2025-01-01,Parts per million,17,100.0,0.028529
1,Alabama,Ozone,2025-01-01,Parts per million,17,100.0,0.025529
2,Alaska,Ozone,2025-01-01,Parts per million,17,100.0,0.041000
3,Arizona,Ozone,2025-01-01,Parts per million,17,100.0,0.041588
4,Arizona,Ozone,2025-01-01,Parts per million,17,100.0,0.030471
...,...,...,...,...,...,...,...
112485,Wyoming,Ozone,2025-04-30,Parts per million,17,100.0,0.042882
112486,Wyoming,Ozone,2025-04-30,Parts per million,17,100.0,0.043118
112487,Puerto Rico,Ozone,2025-04-30,Parts per million,15,88.0,0.003600
112488,Country Of Mexico,Ozone,2025-04-30,Parts per million,17,100.0,0.037059
112489,Country Of Mexico,Ozone,2025-04-30,Parts per million,17,100.0,0.047059

In [11]:
df_so224 = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/dailySO2_42401_2024.csv')
df_so224

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Sulfur dioxide,2024-01-01,Parts per billion,24,100.0,1.041667
1,Alabama,Sulfur dioxide,2024-01-02,Parts per billion,24,100.0,1.537500
2,Alabama,Sulfur dioxide,2024-01-03,Parts per billion,24,100.0,3.716667
3,Alabama,Sulfur dioxide,2024-01-04,Parts per billion,24,100.0,1.237500
4,Alabama,Sulfur dioxide,2024-01-05,Parts per billion,24,100.0,1.200000
...,...,...,...,...,...,...,...
268197,Puerto Rico,Sulfur dioxide,2024-10-25,Parts per billion,8,100.0,0.487500
268198,Puerto Rico,Sulfur dioxide,2024-10-26,Parts per billion,8,100.0,0.425000
268199,Puerto Rico,Sulfur dioxide,2024-10-27,Parts per billion,8,100.0,0.512500
268200,Puerto Rico,Sulfur dioxide,2024-10-28,Parts per billion,8,100.0,0.537500
268201,Puerto Rico,Sulfur dioxide,2024-10-29,Parts per billion,4,50.0,0.600000

In [12]:
df_so225 = pd.read_csv('/Users/cawenosu/Downloads/IS 477 Air quality dataset/daily_SO2_42401_2025.csv')
df_so225

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,Sulfur dioxide,2025-01-01,Parts per billion,24,100.0,0.850000
1,Alabama,Sulfur dioxide,2025-01-01,Parts per billion,8,100.0,0.812500
2,Alabama,Sulfur dioxide,2025-01-01,Parts per billion,24,100.0,-0.104167
3,Alabama,Sulfur dioxide,2025-01-01,Parts per billion,8,100.0,-0.087500
4,Alabama,Sulfur dioxide,2025-01-01,Parts per billion,23,96.0,0.256522
...,...,...,...,...,...,...,...
84496,Wyoming,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,0.787500
84497,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,24,100.0,0.000000
84498,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,0.000000
84499,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,24,100.0,2.741667
84500,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,2.700000

In [13]:
df= pd.concat([df_pm2524, df_pm2525, df_co24, df_co25, df_no224,df_no225, df_ozone24,df_ozone25, df_so224, df_so225], ignore_index=True)
df

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean
0,Alabama,PM2.5 - Local Conditions,2024-01-02,Micrograms/cubic meter (LC),10,42.0,8.410000
1,Alabama,PM2.5 - Local Conditions,2024-01-03,Micrograms/cubic meter (LC),24,100.0,7.420833
2,Alabama,PM2.5 - Local Conditions,2024-01-04,Micrograms/cubic meter (LC),24,100.0,6.933333
3,Alabama,PM2.5 - Local Conditions,2024-01-05,Micrograms/cubic meter (LC),24,100.0,7.900000
4,Alabama,PM2.5 - Local Conditions,2024-01-06,Micrograms/cubic meter (LC),24,100.0,1.270833
...,...,...,...,...,...,...,...
2230814,Wyoming,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,0.787500
2230815,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,24,100.0,0.000000
2230816,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,0.000000
2230817,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,24,100.0,2.741667
2230818,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,2.700000

In [14]:
df_all = df.copy()

In [15]:
df_all["Date Local"] = df_all["Date Local"].astype(str).str.strip()

In [16]:
df_all["Month"] = pd.to_datetime(
    df_all["Date Local"],
    format="%Y-%m-%d",
    errors="coerce"
).dt.month_name()

In [17]:
df_all

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean,Month
0,Alabama,PM2.5 - Local Conditions,2024-01-02,Micrograms/cubic meter (LC),10,42.0,8.410000,January
1,Alabama,PM2.5 - Local Conditions,2024-01-03,Micrograms/cubic meter (LC),24,100.0,7.420833,January
2,Alabama,PM2.5 - Local Conditions,2024-01-04,Micrograms/cubic meter (LC),24,100.0,6.933333,January
3,Alabama,PM2.5 - Local Conditions,2024-01-05,Micrograms/cubic meter (LC),24,100.0,7.900000,January
4,Alabama,PM2.5 - Local Conditions,2024-01-06,Micrograms/cubic meter (LC),24,100.0,1.270833,January
...,...,...,...,...,...,...,...,...
2230814,Wyoming,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,0.787500,April
2230815,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,24,100.0,0.000000,April
2230816,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,0.000000,April
2230817,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,24,100.0,2.741667,April
2230818,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,2.700000,April

In [18]:
def get_quarter_label(month):
    if pd.isna(month):
        return None
    
    if month in ['January','February', 'March']:
        return f"January-March 2024"
    elif month in ['April','May','June']:
        return f"April-June 2024"
    elif month in ['July','August','September']:
        return f"July-September 2024"
    else:
        return f"October-December 2024"

df_all["Quarter"] = df_all["Month"].apply(get_quarter_label)

In [19]:
df_all

,State Name,Parameter Name,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean,Month,Quarter
0,Alabama,PM2.5 - Local Conditions,2024-01-02,Micrograms/cubic meter (LC),10,42.0,8.410000,January,January-March 2024
1,Alabama,PM2.5 - Local Conditions,2024-01-03,Micrograms/cubic meter (LC),24,100.0,7.420833,January,January-March 2024
2,Alabama,PM2.5 - Local Conditions,2024-01-04,Micrograms/cubic meter (LC),24,100.0,6.933333,January,January-March 2024
3,Alabama,PM2.5 - Local Conditions,2024-01-05,Micrograms/cubic meter (LC),24,100.0,7.900000,January,January-March 2024
4,Alabama,PM2.5 - Local Conditions,2024-01-06,Micrograms/cubic meter (LC),24,100.0,1.270833,January,January-March 2024
...,...,...,...,...,...,...,...,...,...
2230814,Wyoming,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,0.787500,April,April-June 2024
2230815,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,24,100.0,0.000000,April,April-June 2024
2230816,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,0.000000,April,April-June 2024
2230817,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,24,100.0,2.741667,April,April-June 2024
2230818,Puerto Rico,Sulfur dioxide,2025-04-30,Parts per billion,8,100.0,2.700000,April,April-June 2024